from typing import Protocol


class TextSourcePort(Protocol):
    """Provides text from the current user selection/context."""

    def retrieve_text(self) -> str: ...


class TriggerControllerPort(Protocol):
    """Runs a trigger loop that dispatches user commands."""

    def run(self) -> None: ...


class SpeechControlPort(Protocol):
    """High-level speech controls invoked by trigger adapters."""

    def start_speaking(self) -> None: ...
    def stop_speaking(self) -> None: ...
    def speak_current_sentence(self) -> None: ...
    def speak_next_sentence(self) -> None: ...
    def speak_prev_sentence(self) -> None: ...
    def increment_rate_up(self) -> None: ...
    def increment_rate_down(self) -> None: ...


class SpeechPort(Protocol):
    """Low-level speech engine operations used by SpeechController."""

    def speak(self, text: str, rate_added: int) -> None: ...
    def stop(self) -> None: ...
    def wait_until_done(self) -> None: ...
